language: python
python:
  - "2.7"
# use pre-compiled system wide packages
# http://danielnouri.org/notes/2012/11/23/use-apt-get-to-install-python-dependencies-for-travis-ci/
virtualenv:
  system_site_packages: true
# command to install system dependencies
before_script:
  - sudo mkdir -p /etc/apache2/mods-available/
  - sudo bash install.ubuntu.sh
  - pip install --upgrade --requirement requirements.txt
#  - pip install --upgrade Pillow
#  - pip install --upgrade Image
#  - pip install --upgrade numpy
#  - pip install --upgrade scipy
#  - pip install --upgrade matplotlib
#  - pip install --upgrade MySQL-python
# command to install python dependencies
install:
  - mkdir data
  - cp config.template data/config.py
# command to run tests
script:
#no login no ssl
  - python ibrowser.py data/ init
  - cat data/config.py
#  - python ibrowser.py data/ adduser test1 pass1
#  - python ibrowser.py data/ adduser test2 pass2
#  - python ibrowser.py data/ listusers
#  - python ibrowser.py data/ deluser test1
#  - python ibrowser.py data/ deluser test2
  - python ibrowser.py data/ clean
#with login no ssl
  - python ibrowser.py data/ init
  - sed -i 's/HAS_LOGIN    = False/HAS_LOGIN    = True/'       data/config.py
  - cat data/config.py
  - python ibrowser.py data/ adduser test1 pass1
  - python ibrowser.py data/ adduser test2 pass2
  - python ibrowser.py data/ listusers
  - python ibrowser.py data/ deluser test1
  - python ibrowser.py data/ deluser test2
  - python ibrowser.py data/ clean
#with login with ssh
  - sed -i 's/USE_SSL        = False/s/USE_SSL        = True'  data/config.py
  - cat data/config.py
  - python ibrowser.py data/ adduser test1 pass1
  - python ibrowser.py data/ adduser test2 pass2
  - python ibrowser.py data/ listusers
  - python ibrowser.py data/ deluser test1
  - python ibrowser.py data/ deluser test2
  - python ibrowser.py data/ clean
#no login with ssh
#  - sed -i 's/HAS_LOGIN    = True/HAS_LOGIN    = False/'       data/config.py
#  - cat data/config.py
#  - python ibrowser.py data/ adduser test1 pass1
#  - python ibrowser.py data/ adduser test2 pass2
#  - python ibrowser.py data/ listusers
#  - python ibrowser.py data/ deluser test1
#  - python ibrowser.py data/ deluser test2
#  - python ibrowser.py data/ clean
#  - python ibrowser.py data/ &
#  - pid=$! && echo PID && sleep 60s && kill -9 $pid && true"
