language: python
python:
  - "2.7"
# command to install system dependencies
before_script:
  - sudo mkdir -p /etc/apache2/mods-available/
  - sudo bash install.ubuntu.sh
  - pip install --upgrade --requirement requirements.txt
  - pip install --upgrade Pillow
  - pip install --upgrade Image
  - pip install --upgrade numpy
  - pip install --upgrade scipy
  - pip install --upgrade matplotlib
  - pip install --upgrade MySQL-python
# command to install python dependencies
install:
  - mkdir data
  - cp config.template data/config.py
# command to run tests
script:
  - python ibrowser.py data/ init
  - sed -i 's/HAS_LOGIN    = False/HAS_LOGIN    = True/' data/config.py
  - cat data/config.py
  - python ibrowser.py data/ adduser test1
  - python ibrowser.py data/ adduser test2
  - python ibrowser.py data/ listusers
  - python ibrowser.py data/ deluser test1
  - python ibrowser.py data/ deluser test2
  - python ibrowser.py data/ clean
  - python ibrowser.py data/
